project:
  type: website

prefer-html: true

website:
  title: "proyecto dsRNA"
  navbar:
    right:
      - about.qmd

      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
format:
  html:
    theme: cosmo
    pdf:
    toc: false
    number-sections: false
    colorlinks: true
    pipersize: letter
  
execute: 
  css: styles.css
  freeze: true

editor: visual




